document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("    <meta name=\'description\' content=\'\'>");
document.writeln("    <meta name=\'author\' content=\'\'>");
document.writeln("");
document.writeln("    <title>Revaya Technology Co., Ltd.</title>");
document.writeln("<link rel=\'Shortcut icon\' href=\'image/ctl.ico\' type=\'image/x-icon\'>");
document.writeln("");
document.writeln("    <!-- Bootstrap Core CSS -->");
document.writeln("    <link href=\'css/bootstrap.css\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("    <!-- Custom CSS -->");
document.writeln("    <link href=\'css/modern-business.css\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("    <!-- Custom Fonts -->");
document.writeln("    <link href=\'font-awesome/css/font-awesome.css\' rel=\'stylesheet\' type=\'text/css\'>");
document.writeln("");
document.writeln("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->");
document.writeln("    <!-- WARNING: Respond.js doesn\'t work if you view the page via file:// -->");
document.writeln("    <!--[if lt IE 9]>");
document.writeln("        <script src=\'https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\'></script>");
document.writeln("        <script src=\'https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\'></script>");
document.writeln("    <![endif]-->");