document.writeln("<nav class=\'navbar navbar-inverse navbar-fixed-top\' role=\'navigation\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <!-- Brand and toggle get grouped for better mobile display -->");
document.writeln("            <div class=\'navbar-header\'>");
document.writeln("                <button type=\'button\' class=\'navbar-toggle\' data-toggle=\'collapse\' data-target=\'#bs-example-navbar-collapse-1\'>");
document.writeln("                    <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("                    <span class=\'icon-bar\'></span>");
document.writeln("                    <span class=\'icon-bar\'></span>");
document.writeln("                    <span class=\'icon-bar\'></span>");
document.writeln("                </button>");
document.writeln("                <a class=\'navbar-brand\' href=\'index.html\'>嘉明利科技股份有限公司</a>");
document.writeln("            </div>");
document.writeln("            <!-- Collect the nav links, forms, and other content for toggling -->");
document.writeln("            <div class=\'collapse navbar-collapse\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("                <ul class=\'nav navbar-nav navbar-right\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'about-ch.html\'>關於我們</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'services-ch.html\'>服務</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'contact-ch.html\'>聯絡我們</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>產品 <b class=\'caret\'></b></a>");
document.writeln("                        <ul class=\'dropdown-menu\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'acroview-ch.html\'>昂科</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'Elnec-ch.html\'>Elnec</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'Minato-ch.html\'>Minato</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'sb-ch.html\'>隔離箱</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'MT-1040-ch.html\'>無線產品測試</a>");
document.writeln("                            </li>   ");
document.writeln("                            <li class=\'active\'>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'dropdown\'>");
document.writeln("                      <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>語言 Languages <b class=\'caret\'></b></a>");
document.writeln("                        <ul class=\'dropdown-menu\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'index.html\'>繁體中文</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'index-en.html\'>English</a>");
document.writeln("                            </li>");
document.writeln("");
document.writeln("                        </ul>                    </li>");
document.writeln("                    <li class=\'dropdown\'>");
document.writeln("                        <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>嘉多利集團  <img width=8% src=\'image/ctl.png\'><b class=\'caret\'></b></a>");
document.writeln("                        <ul class=\'dropdown-menu\'>");
document.writeln("                            <li>");
document.writeln("                                <a target=\'_blank\' href=\'http://www.dgtclp.com/index.html\'>東莞嘉多利</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a target=\'_blank\' href=\'http://www.clpe.com.cn/home/index\'>蘇州嘉多利</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\' http://www.programtek.com.cn/\'>蘇州普利明</a>");
document.writeln("                            </li>");
document.writeln("                          </ul>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <!-- /.navbar-collapse -->");
document.writeln("        </div>");
document.writeln("        <!-- /.container -->");
document.writeln("    </nav>");
document.writeln("");
